CONFIG_ZMK_SPLIT_ROLE_CENTRAL=y

# Uncomment to enable RGB
CONFIG_ZMK_RGB_UNDERGLOW=y
CONFIG_ZMK_RGB_UNDERGLOW_EXT_POWER=n
#CONFIG_ZMK_RGB_UNDERGLOW_ON_START=n
CONFIG_ZMK_RGB_UNDERGLOW_BRT_START=20
CONFIG_ZMK_RGB_UNDERGLOW_BRT_MAX=50
CONFIG_ZMK_RGB_UNDERGLOW_EFF_START=1